site_name: Sensor Apple (820-1893-A) with Raspberry Pi PICO and python
site_url: "https://rhinosys.github.io/temp-pico-apple/"
dev_addr: '127.0.0.1:8888'
theme:
  hljs_languages:
        - yaml
        - rust
  name: material
  features:
    - toc.integrate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        en: English
        fr: Français
 - glightbox:
   touchNavigation: true
   loop: false
   effect: zoom
   slide_effect: slide
   width: 100%
   height: auto
   zoomable: true
   draggable: true
   skip_classes:
     - custom-skip-class-name
   auto_caption: true
   caption_position: bottom
#  - encryptcontent:
#      title_prefix: '[LOCK]'
#      summary: 'another informational message to encrypted content'
#      placeholder: 'Wise2020!'
#      decryption_failure_message: 'another informational message when decryption fail'
#      encryption_info_message: 'another information message when you dont have acess !'
#      password_button: True
#      password_button_text: 'custome_text_button'
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - meta
  - attr_list
  - md_in_html
  - codehilite
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
extra_css:
- css/termynal.css
- css/custom.css
